name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start mock server
        run: node server.js &

      - name: Run tests
        run: npm test

      # 🚦 QUALITY GATE (crítico)
      - name: Check test result
        if: failure()
        run: exit 1

      - name: Generate Allure Report
        run: npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/